### ISSUE TITLE
編碼意見

### ISSUE THREAD

**Issue by Oscar142857** [LEOYoon-Tsaw/Cangjie6#10]
-----------------
原碼
㚇	uche
𡕰	uche
𡶣	uche
-----------------

三字編碼相同，建議如下：
㚇：ukche  (無重碼)
𡕰：uiche   (無重碼)    => (ref: 鬯	uip)
𡶣：uche    (無重碼)

敬納。

**Comment by LEOYoon-Tsaw** [comment]
無重碼並非目的，儍是人山金水，傻是人竹金水，右邊第二碼都是金。
我不會為了減少幾個罕用字重碼創造新規則
