### ISSUE TITLE
關於「𫧙」的編碼

### ISSUE THREAD

**Issue by szieziw** [LEOYoon-Tsaw/Cangjie6#12]
unicode：2B9D9，應該是「尸火一木」。

**Comment by TNTErick** [comment]
鳥在六代取作「的片」，據百度倉頡吧吧友推測，「![image](https://user-images.githubusercontent.com/30978340/205481529-4bba6f85-034f-45aa-8b13-c8f339f03748.png)」爲片的字根。取「尸片一木」無誤。

**Comment by LEOYoon-Tsaw** [comment]
<img width="152" alt="image" src="https://user-images.githubusercontent.com/4469383/205496304-fee14396-f919-4f66-9269-e207dbd3cbab.png">
是烏非鳥
