### ISSUE TITLE
「連」的反查

### ISSUE THREAD

**Issue by erstern** [LEOYoon-Tsaw/Cangjie6#2]
poly 版的拼音中，「連」是「lien」，我照搬了 Cangjie6 方案裏的反查，結果是 `〖來〗重紐四等開【仙】平` ；而在韻書和韻圖中查到的均是三等。
請問是反查方案中正則式的問題还是有其他特別的原因？

**Comment by LEOYoon-Tsaw** [comment]
重紐四等就是重紐A類，建議你瞭解一下「重紐」
