### ISSUE TITLE
平時使用時，慢慢加入了這些編碼，請幫忙查檢下，評價一下取捨

### ISSUE THREAD

**Issue by Fszhouzz** [LEOYoon-Tsaw/Cangjie6#3]
你好，我用一個蒼六的碼表，然後整合了你的碼表，平時使用時，慢慢加入了這些編碼。
請幫忙查檢下，評價一下取捨。看是可以加入碼表，爲什麼。謝謝。
ityi  𠦑
jiti  𡨜
titi  𦯂
diti  𣓙
diti  𣒏
itiu  𥆳
itiv  𧚛
rxiti 𨁕
ams 昈
bmm  ⺜
ambg 𪱑
amsf 𤋁
arhdr ㍼
bimgi 𤦼
dm    
dmoig ㍿
dwali 𧖤
ewfg 濹
fpa  𤈎
hh 
hxu 龜
immgi 鿑
inf  礻
ipvs 𢍻
ixpf 𢊁
jv 𫠠
ksh  犭
llsb  帰
lxs 
m ー
mrem 亟
mu 兀
ni 々
nmby 鿕
ns ㇡
onqd 𣔕
opmrr 鿔
qsopj 𮧵
rysy  唹
smle 𠭙
ssmaa 𦑾
tlqo 𦰩
tmbo 鿒
tmbz 鿓
tovu 荒
wibp 愚
wx   𡆵
xkkr 𥕭
xkkt 𥂞
xysc 與
yhsm 𨒎
yonk 夜
ysm 𨒎
yybuc 𧹂
yybuu 𬢆
zzau ↑
zzyp ˉ
zzyq ˙
mm ⚋
m ⚊
aaa ☰
baa ☱
aba ☲
bba ☳
aab ☴
bab ☵
abb ☶
bbb ☷
mmm ☰
cmm ☱
mcm ☲
ccm ☳
mmc ☴
cmc ☵
mcc ☶
ccc ☷
tm ☱
mt ☲
ct ☳
tc ☵

**Comment by LEOYoon-Tsaw** [comment]
感謝你提供的編碼，漢字部份我會考慮的

**Comment by LEOYoon-Tsaw** [comment]
六十四卦和八卦顯然用符號檢索更合理，不支持編碼；此外「㍼、㍿、⺜、々」同樣更偏符號，而非漢字。「𤦼、𣔕、𤈎」是明確的重複收字，不收（加#放在字典前面了）；兀在兼容區，又非獨立漢字，不收；「𮧵」在擴展F區，等統一加入。其它的基本都採納了🙂️
