### ISSUE TITLE
請看一下，我自已編碼了F區的漢字，又查改了兩遍

### ISSUE THREAD

**Issue by Fszhouzz** [LEOYoon-Tsaw/Cangjie6#4]
請看一下，我自已編碼了F區的漢字，又查改了兩遍。請看一下有什麼問題。
請主要看看《蒼頡六統一碼擴展F區漢字》《蒼頡六網友碼表補充》的內容，其他也可以看看有不有問題。
《蒼頡六網友碼表補充》中的，是對你的碼表的一些补充，請評價下取捨。
《蒼頡編碼說明.txt》是我編碼F區漢字的過程中，收集的一些東西。
我的地址如下：
https://github.com/fszhouzzOrgOne/Cangjie6Coding.git
謝謝。

**Comment by Fszhouzz** [comment]
如果有問題的地方，請指出來我改正。如果最後改好了，能請收入你的碼表就好了。
《蒼頡六網友碼表補充》中的一些符號，可以不管它們。

**Comment by Fszhouzz** [comment]
如xkkt 𥂞，我改成了xkbt。

**Comment by LEOYoon-Tsaw** [comment]
太感謝了！我會盡快合併的👍🏻
