### ISSUE TITLE
关于 6 代的一些疑问

### ISSUE THREAD

**Issue by nasyxx** [LEOYoon-Tsaw/Cangjie6#6]
非常感谢您的制作。

6代似乎一直没有正式发布...最近有一些疑问，不知道是否该继续使用6代，还是回去使用5代。

主要疑问是这个：
**为甚么 scheme 里面 h 依然是 "竹" 而不是 "的"？**

**z 似乎也不能直接给出 "片"？** （虽然可以自己加上去)

scheme：
https://github.com/LEOYoon-Tsaw/Cangjie6/blob/master/cangjie6.schema.yaml#L94

我看到网络上 h 已经改为"的"了。 dict 里面，h 也是"的"，"竹" 是 "olol"。

还有 z 是"片"，但似乎 dict 里面依然用着 "llml"，或者 "llms"，而不是5代的 "llmn"。

-----

另一方面6的字比5要全一些，也许我该把5与6的dict混合使用。

**Comment by LEOYoon-Tsaw** [comment]
h是的，輸入是的，顯示為竹是我做的滯古，你可以改。z只是顯示為片，但「片」這個字型從來不用z，z不能單用，片可以理解為「不完整的部件」，並非其字型。

**Comment by nasyxx** [comment]
> 但「片」這個字型從來不用z，z不能單用，片可以理解為「不完整的部件」，並非其字型。

原来如此，谢谢。
