### ISSUE TITLE
關於“𩍫”的編碼

### ISSUE THREAD

**Issue by szieziw** [LEOYoon-Tsaw/Cangjie6#9]
這個字在漢語大字典中的字形應編成“廿十月中水”，希望加上這個編碼

**Comment by LEOYoon-Tsaw** [comment]
<img width="257" alt="image" src="https://user-images.githubusercontent.com/4469383/176936278-c5286fd6-5e44-4a9e-a571-508885d842cb.png">
已修改 https://github.com/LEOYoon-Tsaw/Cangjie6/commit/39a9328a873f17856de64654e9e6365ce3e1d716
